---
name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - run: npx jest --coverage

      - uses: actions/upload-artifact@v3
        with:
          name: "report"
          path: "coverage/coverage-final.json"

  # sanity-e2e:
  #   name: End to End Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         build: npm run build
  #         start: npm run start:ci
  #         wait-on: "http://localhost:3000/"
  #         wait-on-timeout: 120
  #         parallel: true
  #         record: true
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - run: |
  #         mv coverage/coverage-final.json coverage/coverage.${{ matrix.containers }}.json
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: "report"
  #         path: "coverage/coverage.${{ matrix.containers }}.json"

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: [unit]
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Download and move artifacts
  #       uses: actions/download-artifact@v2
  #     - run: |
  #         mkdir .nyc_output
  #         npx nyc merge report
  #         mv coverage.json .nyc_output/out.json
  #         ls .nyc_output
  #         ls report
  #         # npx nyc report --reporter lcov --reporter text --report-dir coverage --exclude-after-remap false

  #     - uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         threshold: 74
  #         skip-step: all
  #         coverage-file: ".nyc_output/out.json"
  #         base-coverage-file: "report/coverage-final.json"
  #         annotations: coverage

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: "coverage"
  #         path: "coverage"
