---
name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

jobs:
  unit:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - run: npx jest --coverage

      - uses: actions/upload-artifact@v3
        with:
          name: "report"
          path: "coverage/coverage-final.json"

  e2e:
    name: End to End Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build next
        run: npm run build

      - name: Cypress run
        run: npm run integration

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: "report"
      #     path: "coverage/coverage-final.json"
      - run: |
          mv cypress-coverage/coverage-final.json cypress-coverage/coverage.e2e.json
      - uses: actions/upload-artifact@v3
        with:
          name: "report"
          path: "cypress-coverage/coverage.e2e.json"

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [unit, e2e]
    steps:
      - uses: actions/checkout@v3

      - name: Download and move artifacts
        uses: actions/download-artifact@v2

      - run: ls

      - run: |
          mkdir .nyc_output
          npx nyc merge report
          mv coverage.json .nyc_output/out.json
          ls .nyc_output
          ls report
          npx nyc report --reporter lcov --reporter text --reporter json-summary --report-dir coverage --exclude-after-remap false

      - name: Coverage Diff
        uses: ./.github/actions/diff
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-to-fail: "true"

      - uses: actions/upload-artifact@v3
        with:
          name: "coverage"
          path: "coverage"
